### ISSUE TITLE
Change trigger and images calculation model

### ISSUE THREAD

**Issue by frmadem** [prefapp/action-deployment-dispatch#19]
# Motivation

We need to redesign the deployment model making it a more individual and independent process. 

<img width="822" alt="image" src="https://user-images.githubusercontent.com/6397709/179958843-f8bb0d15-cb44-4e39-a58c-6b778bc27860.png">

Therefore, now, the deployment process should calculate ALL the images to dispatch to the state's repo. 

It should emit one event with all the images every microservice should have. 

Thus, we need a reconciliation process on the state's repo side to ensure the proper version of every microservice. 

## Acceptance criteria

- [x] The action is able to calculate all the versions according to its deployment.yaml file. 
- [x] The action is able to dispatch one event with all the versions. 
- [ ] The prefapp teams validates and approves the changes.

**Comment by alambike** [comment]
Related https://github.com/prefapp/action-state-repo-update-image/pull/85, thanks to @AlbertoFemenias .
