### ISSUE TITLE
Label the PR to achieve idempotency

### ISSUE THREAD

**Issue by alambike** [prefapp/action-deployment-dispatch#21]
### Motivation

We need to add the deployment coordinates to the deployment PR
- tenant
- environment
- application
- service_name

In this way, we could check, before creating a new PR, that a previous PR deployment exists, and, in that case, update that PR instead of opening a new one, to avoid confusion for the platform team with the manual-approval PRs.

If the labels don't exist, they should be created, if possible!?

**Comment by AlbertoFemenias** [comment]
Superseded by https://github.com/prefapp/action-state-repo-update-image/issues/89
